<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "files".
 *
 * @property int $id
 * @property int $cat_id
 * @property int $name
 * @property string $path
 * @property int|null $active
 */
class File extends \yii\db\ActiveRecord
{
    public $file;
    const FILE_ACTIVE = ['1' => 'Активен', '0' => 'Не активен'];
    const FUEL = [
        '0' => 'Бензин',
        '1' => 'Дизель',
        '2' => 'Гибрид',
        '3' => 'Электро'];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'files';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cat_id', 'active', 'brand_id', 'model_id', 'fuel'], 'integer'],
            [['name'], 'string', 'max' => 500],
            [['path'], 'string', 'max' => 500],
            [['motor'], 'string', 'max' => 40],
            [['file'], 'file'],
            [['price'], 'number'],
            [['desc_ru'], 'safe'],
            [['desc_en'], 'safe'],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cat_id' => 'Cat ID',
            'brand_id' => 'Марка авто',
            'model_id' => 'Модель авто',
            'motor' => 'Марка двигателя',
            'fuel' => 'Вид топлива',
            'name' => 'Название',
            'path' => 'Путь к файлу',
            'active' => 'Активность',
            'price' => 'Цена',
            'desc_ru' => 'Описание файла на русском',
            'desc_en' => 'Описание файла на английском',
        ];
    }

    public function getCategory(){
        return $this->hasOne(Category::className(), ['id'=>'cat_id']);
    }

    static public function byCategory($catid){
        return File::find()->where(["cat_id"=>$catid])->all();
    }

    public function beforeSave($insert)
    {
        if ($this->file) {
            $this->path = 'uploads/' . $this->file->baseName . '.' . $this->file->extension;
            $this->file->saveAs($this->path);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
