<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user_files".
 *
 * @property int $user_id
 * @property int $file_id
 * @property int $status
 */
class UserFile extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_files';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'file_id'], 'required'],
            [['user_id', 'file_id', 'status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'user_id' => 'User ID',
            'file_id' => 'File ID',
            'status' => 'Status',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

    }

    public function getFile(){
        return $this->hasOne(File::className(), ['id'=>'file_id']);
    }
}


